volumes:
  sqlserver:


version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    hostname: mssql.philcompton.dev
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ChangeMePlease!
    volumes:
      - sqlserver:/var/opt/mssql